# Generated by Django 5.0.3 on 2024-03-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['complete', 'deadline']},
        ),
    ]
